### ISSUE TITLE
Arch linux not supported

### ISSUE THREAD

**Issue by gual** [epicweb-dev/react-server-components#20]
:wave:

**Issue**
If my reading is correct, Playwright is used for the tests, my main station has an Arch Linux so the setup fails. Playwright only supports:
```
* Windows 10+, Windows Server 2016+ or Windows Subsystem for Linux (WSL).
* macOS 13 Ventura, or later.
* Debian 12, Ubuntu 22.04, Ubuntu 24.04, on x86-64 and arm64 architecture.
```
[System requirements](https://playwright.dev/docs/intro#system-requirements)
[Closed Arch linux support issue](https://github.com/microsoft/playwright/issues/30393)

**Possible solution**
I'm know using a different tool for tests might be out of scope but it would be useful to have the OS listed in the README's _System Requirements_ section

**Comment by kentcdodds** [comment]
Yes, unfortunately this is a limitation of playwright. I think it is out of scope to list it in the README because it would be confusing to say linux isn't supported when it's actually just the tests which aren't supported. Everything else works well.

That said, if you want to make a pull request to add a note, then I may look at it. I'll close this for now though. Thanks!
